// AUTO-GENERATED by scripts/sync-templates.ts — do not edit.
// Keep this file committed as the offline build-time fallback.
// Regenerate before release: pnpm run sync-templates
//
// Source:  https://github.com/BadKid90s/conf-template/tree/main/conf/1.13.8/zh-cn
// Branch:  main
// Commit:  b5e4d3de60b0afb04f66a6d2114ad540ae18b701
// Built:   2026-06-30T00:56:14.402Z
// sing-box: v1.13.13

import type { configType } from '../common';

export const BUILD_TIME_TEMPLATE_SOURCE = {
    repo: 'BadKid90s/conf-template',
    branch: 'main',
    commit: 'b5e4d3de60b0afb04f66a6d2114ad540ae18b701',
    versionPath: '1.13.8',
    singBoxVersion: 'v1.13.13',
    generatedAt: '2026-06-30T00:56:14.402Z',
} as const;

export const MIXED_TEMPLATE = {
    "log": {
        "disabled": false,
        "level": "debug",
        "timestamp": false
    },
    "dns": {
        "servers": [
            {
                "tag": "system",
                "type": "udp",
                "server": "119.29.29.29",
                "server_port": 53,
                "connect_timeout": "5s"
            },
            {
                "tag": "dns_proxy",
                "type": "tcp",
                "server": "1.0.0.1",
                "server_port": 53,
                "detour": "ExitGateway",
                "connect_timeout": "5s"
            }
        ],
        "rules": [
            {
                "query_type": [
                    "HTTPS",
                    "SVCB",
                    "PTR"
                ],
                "action": "reject"
            },
            {
                "domain": [
                    "captive.oneoh.cloud",
                    "captive.apple.com",
                    "nmcheck.gnome.org",
                    "www.msftconnecttest.com",
                    "connectivitycheck.gstatic.com",
                    "sequoia.apple.com",
                    "seed-sequoia.siri.apple.com"
                ],
                "rule_set": [
                    "geoip-cn",
                    "geosite-cn"
                ],
                "strategy": "prefer_ipv4",
                "server": "system"
            }
        ],
        "final": "dns_proxy",
        "strategy": "prefer_ipv4"
    },
    "inbounds": [
        {
            "tag": "mixed",
            "type": "mixed",
            "listen": "127.0.0.1",
            "listen_port": 6789,
            "set_system_proxy": false
        }
    ],
    "route": {
        "rules": [
            {
                "action": "sniff"
            },
            {
                "type": "logical",
                "mode": "or",
                "rules": [
                    {
                        "protocol": "dns"
                    },
                    {
                        "port": 53
                    }
                ],
                "action": "hijack-dns"
            },
            {
                "protocol": "quic",
                "action": "reject"
            },
            {
                "ip_is_private": true,
                "outbound": "direct"
            },
            {
                "domain": [
                    "reject-tag.oneoh.cloud"
                ],
                "action": "reject"
            },
            {
                "domain": [
                    "direct-tag.oneoh.cloud"
                ],
                "outbound": "direct"
            },
            {
                "domain": [
                    "proxy-tag.oneoh.cloud"
                ],
                "outbound": "ExitGateway"
            },
            {
                "domain": [
                    "captive.oneoh.cloud",
                    "captive.apple.com",
                    "nmcheck.gnome.org",
                    "www.msftconnecttest.com",
                    "connectivitycheck.gstatic.com",
                    "sequoia.apple.com",
                    "seed-sequoia.siri.apple.com"
                ],
                "domain_suffix": [
                    "local",
                    "lan",
                    "localdomain",
                    "localhost",
                    "bypass.local",
                    ".oneoh.cloud",
                    ".ksjhaoka.com",
                    ".mixcapp.com"
                ],
                "outbound": "direct",
                "rule_set": [
                    "geoip-cn",
                    "geosite-cn"
                ]
            }
        ],
        "final": "ExitGateway",
        "default_domain_resolver": "system",
        "auto_detect_interface": true,
        "rule_set": [
            {
                "tag": "geoip-cn",
                "type": "remote",
                "format": "binary",
                "url": "https://jsdelivr.oneoh.cloud/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs"
            },
            {
                "tag": "geosite-cn",
                "type": "remote",
                "format": "binary",
                "url": "https://jsdelivr.oneoh.cloud/gh/OneOhCloud/one-geosite@rules/geosite-one-cn.srs"
            }
        ]
    },
    "experimental": {
        "clash_api": {},
        "cache_file": {}
    },
    "outbounds": [
        {
            "tag": "direct",
            "type": "direct",
            "domain_resolver": "system"
        },
        {
            "tag": "ExitGateway",
            "type": "selector",
            "outbounds": [
                "auto"
            ],
            "interrupt_exist_connections": true
        },
        {
            "tag": "auto",
            "type": "urltest",
            "url": "https://www.google.com/generate_204",
            "outbounds": []
        }
    ]
} as const;

export const TUN_TEMPLATE = {
    "log": {
        "disabled": false,
        "level": "debug",
        "timestamp": false
    },
    "dns": {
        "servers": [
            {
                "tag": "system",
                "type": "udp",
                "server": "119.29.29.29",
                "server_port": 53,
                "connect_timeout": "5s"
            },
            {
                "tag": "dns_proxy",
                "type": "tcp",
                "server": "1.0.0.1",
                "server_port": 53,
                "detour": "ExitGateway",
                "connect_timeout": "5s"
            },
            {
                "tag": "remote",
                "type": "fakeip",
                "inet4_range": "198.18.0.0/15",
                "inet6_range": "fc00::/18"
            }
        ],
        "rules": [
            {
                "query_type": [
                    "HTTPS",
                    "SVCB",
                    "PTR"
                ],
                "action": "reject"
            },
            {
                "domain": [
                    "captive.oneoh.cloud",
                    "captive.apple.com",
                    "nmcheck.gnome.org",
                    "www.msftconnecttest.com",
                    "connectivitycheck.gstatic.com",
                    "sequoia.apple.com",
                    "seed-sequoia.siri.apple.com"
                ],
                "rule_set": [
                    "geoip-cn",
                    "geosite-cn"
                ],
                "strategy": "prefer_ipv4",
                "server": "system"
            },
            {
                "query_type": [
                    "A",
                    "AAAA",
                    "CNAME"
                ],
                "server": "remote",
                "strategy": "prefer_ipv4"
            }
        ],
        "final": "dns_proxy",
        "strategy": "prefer_ipv4"
    },
    "inbounds": [
        {
            "tag": "tun",
            "type": "tun",
            "address": [
                "172.19.0.1/30",
                "fdfe:dcba:9876::1/126"
            ],
            "platform": {
                "http_proxy": {
                    "enabled": true,
                    "server": "127.0.0.1",
                    "server_port": 6789
                }
            },
            "mtu": 1500,
            "stack": "gvisor",
            "auto_route": true,
            "strict_route": true,
            "route_exclude_address": [
                "10.0.0.0/8",
                "127.0.0.0/8",
                "169.254.0.0/16",
                "172.16.0.0/12",
                "192.0.0.0/24",
                "192.168.0.0/16",
                "224.0.0.0/4",
                "240.0.0.0/4",
                "255.255.255.255/32",
                "fe80::/10",
                "fc00::/7",
                "ff01::/16",
                "ff02::/16",
                "ff03::/16",
                "ff04::/16",
                "ff05::/16"
            ]
        },
        {
            "tag": "mixed",
            "type": "mixed",
            "listen": "127.0.0.1",
            "listen_port": 6789,
            "set_system_proxy": false
        }
    ],
    "route": {
        "rules": [
            {
                "action": "sniff"
            },
            {
                "type": "logical",
                "mode": "or",
                "rules": [
                    {
                        "protocol": "dns"
                    },
                    {
                        "port": 53
                    }
                ],
                "action": "hijack-dns"
            },
            {
                "protocol": "quic",
                "action": "reject"
            },
            {
                "ip_is_private": true,
                "outbound": "direct"
            },
            {
                "network": "icmp",
                "action": "route",
                "outbound": "direct"
            },
            {
                "domain": [
                    "reject-tag.oneoh.cloud"
                ],
                "action": "reject"
            },
            {
                "domain": [
                    "direct-tag.oneoh.cloud"
                ],
                "outbound": "direct"
            },
            {
                "domain": [
                    "proxy-tag.oneoh.cloud"
                ],
                "outbound": "ExitGateway"
            },
            {
                "domain": [
                    "captive.oneoh.cloud",
                    "captive.apple.com",
                    "nmcheck.gnome.org",
                    "www.msftconnecttest.com",
                    "connectivitycheck.gstatic.com",
                    "sequoia.apple.com",
                    "seed-sequoia.siri.apple.com"
                ],
                "domain_suffix": [
                    "local",
                    "lan",
                    "localdomain",
                    "localhost",
                    "bypass.local",
                    ".oneoh.cloud",
                    ".ksjhaoka.com",
                    ".mixcapp.com"
                ],
                "outbound": "direct",
                "rule_set": [
                    "geoip-cn",
                    "geosite-cn"
                ]
            }
        ],
        "final": "ExitGateway",
        "default_domain_resolver": "system",
        "auto_detect_interface": true,
        "rule_set": [
            {
                "tag": "geoip-cn",
                "type": "remote",
                "format": "binary",
                "url": "https://jsdelivr.oneoh.cloud/gh/MetaCubeX/meta-rules-dat@sing/geo/geoip/cn.srs"
            },
            {
                "tag": "geosite-cn",
                "type": "remote",
                "format": "binary",
                "url": "https://jsdelivr.oneoh.cloud/gh/OneOhCloud/one-geosite@rules/geosite-one-cn.srs"
            }
        ]
    },
    "experimental": {
        "clash_api": {},
        "cache_file": {}
    },
    "outbounds": [
        {
            "tag": "direct",
            "type": "direct",
            "domain_resolver": "system"
        },
        {
            "tag": "ExitGateway",
            "type": "selector",
            "outbounds": [
                "auto"
            ],
            "interrupt_exist_connections": true
        },
        {
            "tag": "auto",
            "type": "urltest",
            "url": "https://www.google.com/generate_204",
            "outbounds": []
        }
    ]
} as const;

export const MIXED_GLOBAL_TEMPLATE = {
    "log": {
        "disabled": false,
        "level": "debug",
        "timestamp": false
    },
    "dns": {
        "servers": [
            {
                "tag": "system",
                "type": "udp",
                "server": "119.29.29.29",
                "server_port": 53,
                "connect_timeout": "5s"
            },
            {
                "tag": "dns_proxy",
                "type": "tcp",
                "server": "1.0.0.1",
                "server_port": 53,
                "detour": "ExitGateway",
                "connect_timeout": "5s"
            }
        ],
        "rules": [
            {
                "query_type": [
                    "HTTPS",
                    "SVCB",
                    "PTR"
                ],
                "action": "reject"
            },
            {
                "domain": [
                    "captive.oneoh.cloud",
                    "captive.apple.com",
                    "nmcheck.gnome.org",
                    "www.msftconnecttest.com",
                    "connectivitycheck.gstatic.com",
                    "sequoia.apple.com",
                    "seed-sequoia.siri.apple.com"
                ],
                "strategy": "prefer_ipv4",
                "server": "system"
            }
        ],
        "final": "dns_proxy",
        "strategy": "prefer_ipv4"
    },
    "inbounds": [
        {
            "tag": "mixed",
            "type": "mixed",
            "listen": "127.0.0.1",
            "listen_port": 6789,
            "set_system_proxy": false
        }
    ],
    "route": {
        "rules": [
            {
                "action": "sniff"
            },
            {
                "type": "logical",
                "mode": "or",
                "rules": [
                    {
                        "protocol": "dns"
                    },
                    {
                        "port": 53
                    }
                ],
                "action": "hijack-dns"
            },
            {
                "protocol": "quic",
                "action": "reject"
            },
            {
                "ip_is_private": true,
                "outbound": "direct"
            },
            {
                "domain": [
                    "captive.oneoh.cloud",
                    "captive.apple.com",
                    "nmcheck.gnome.org",
                    "www.msftconnecttest.com",
                    "connectivitycheck.gstatic.com",
                    "sequoia.apple.com",
                    "seed-sequoia.siri.apple.com"
                ],
                "domain_suffix": [
                    "local",
                    "lan",
                    "localdomain",
                    "localhost",
                    "bypass.local",
                    ".oneoh.cloud",
                    ".ksjhaoka.com",
                    ".mixcapp.com"
                ],
                "outbound": "direct"
            }
        ],
        "final": "ExitGateway",
        "default_domain_resolver": "system",
        "auto_detect_interface": true,
        "rule_set": []
    },
    "experimental": {
        "clash_api": {},
        "cache_file": {}
    },
    "outbounds": [
        {
            "tag": "direct",
            "type": "direct",
            "domain_resolver": "system"
        },
        {
            "tag": "ExitGateway",
            "type": "selector",
            "outbounds": [
                "auto"
            ],
            "interrupt_exist_connections": true
        },
        {
            "tag": "auto",
            "type": "urltest",
            "url": "https://www.google.com/generate_204",
            "outbounds": []
        }
    ]
} as const;

export const TUN_GLOBAL_TEMPLATE = {
    "log": {
        "disabled": false,
        "level": "debug",
        "timestamp": false
    },
    "dns": {
        "servers": [
            {
                "tag": "system",
                "type": "udp",
                "server": "119.29.29.29",
                "server_port": 53,
                "connect_timeout": "5s"
            },
            {
                "tag": "dns_proxy",
                "type": "tcp",
                "server": "1.0.0.1",
                "server_port": 53,
                "detour": "ExitGateway",
                "connect_timeout": "5s"
            },
            {
                "tag": "remote",
                "type": "fakeip",
                "inet4_range": "198.18.0.0/15",
                "inet6_range": "fc00::/18"
            }
        ],
        "rules": [
            {
                "query_type": [
                    "HTTPS",
                    "SVCB",
                    "PTR"
                ],
                "action": "reject"
            },
            {
                "domain": [
                    "captive.oneoh.cloud",
                    "captive.apple.com",
                    "nmcheck.gnome.org",
                    "www.msftconnecttest.com",
                    "connectivitycheck.gstatic.com",
                    "sequoia.apple.com",
                    "seed-sequoia.siri.apple.com"
                ],
                "strategy": "prefer_ipv4",
                "server": "system"
            },
            {
                "query_type": [
                    "A",
                    "AAAA",
                    "CNAME"
                ],
                "server": "remote",
                "strategy": "prefer_ipv4"
            }
        ],
        "final": "dns_proxy",
        "strategy": "prefer_ipv4"
    },
    "inbounds": [
        {
            "tag": "tun",
            "type": "tun",
            "address": [
                "172.19.0.1/30",
                "fdfe:dcba:9876::1/126"
            ],
            "platform": {
                "http_proxy": {
                    "enabled": true,
                    "server": "127.0.0.1",
                    "server_port": 6789
                }
            },
            "mtu": 1500,
            "stack": "gvisor",
            "auto_route": true,
            "strict_route": true,
            "route_exclude_address": [
                "10.0.0.0/8",
                "127.0.0.0/8",
                "169.254.0.0/16",
                "172.16.0.0/12",
                "192.0.0.0/24",
                "192.168.0.0/16",
                "224.0.0.0/4",
                "240.0.0.0/4",
                "255.255.255.255/32",
                "fe80::/10",
                "fc00::/7",
                "ff01::/16",
                "ff02::/16",
                "ff03::/16",
                "ff04::/16",
                "ff05::/16"
            ]
        },
        {
            "tag": "mixed",
            "type": "mixed",
            "listen": "127.0.0.1",
            "listen_port": 6789,
            "set_system_proxy": false
        }
    ],
    "route": {
        "rules": [
            {
                "action": "sniff"
            },
            {
                "type": "logical",
                "mode": "or",
                "rules": [
                    {
                        "protocol": "dns"
                    },
                    {
                        "port": 53
                    }
                ],
                "action": "hijack-dns"
            },
            {
                "protocol": "quic",
                "action": "reject"
            },
            {
                "ip_is_private": true,
                "outbound": "direct"
            },
            {
                "network": "icmp",
                "action": "route",
                "outbound": "direct"
            },
            {
                "domain": [
                    "captive.oneoh.cloud",
                    "captive.apple.com",
                    "nmcheck.gnome.org",
                    "www.msftconnecttest.com",
                    "connectivitycheck.gstatic.com",
                    "sequoia.apple.com",
                    "seed-sequoia.siri.apple.com"
                ],
                "domain_suffix": [
                    "local",
                    "lan",
                    "localdomain",
                    "localhost",
                    "bypass.local",
                    ".oneoh.cloud",
                    ".ksjhaoka.com",
                    ".mixcapp.com"
                ],
                "outbound": "direct"
            }
        ],
        "final": "ExitGateway",
        "default_domain_resolver": "system",
        "auto_detect_interface": true,
        "rule_set": []
    },
    "experimental": {
        "clash_api": {},
        "cache_file": {}
    },
    "outbounds": [
        {
            "tag": "direct",
            "type": "direct",
            "domain_resolver": "system"
        },
        {
            "tag": "ExitGateway",
            "type": "selector",
            "outbounds": [
                "auto"
            ],
            "interrupt_exist_connections": true
        },
        {
            "tag": "auto",
            "type": "urltest",
            "url": "https://www.google.com/generate_204",
            "outbounds": []
        }
    ]
} as const;

export const BUILT_IN_TEMPLATE_OBJECTS: Record<configType, unknown> = {
    'mixed': MIXED_TEMPLATE,
    'tun': TUN_TEMPLATE,
    'mixed-global': MIXED_GLOBAL_TEMPLATE,
    'tun-global': TUN_GLOBAL_TEMPLATE,
};
