#!/usr/bin/env tsx
import { parse as parseJsonc } from 'jsonc-parser';
import { existsSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, resolve } from 'node:path';
import { fileURLToPath } from 'node:url';
import { SING_BOX_MAJOR_VERSION, SING_BOX_MINOR_VERSION, SING_BOX_VERSION } from '../src/types/definition';

const REPO = process.env.CONF_TEMPLATE_REPO ?? 'BadKid90s/conf-template';
const BRANCH = process.env.CONF_TEMPLATE_BRANCH ?? 'main';

const MODE_TO_FILE: Record<string, string> = {
    'mixed': 'mixed-rules.jsonc',
    'tun': 'tun-rules.jsonc',
    'mixed-global': 'mixed-global.jsonc',
    'tun-global': 'tun-global.jsonc',
};

const __dirname = dirname(fileURLToPath(import.meta.url));
const OUTPUT_PATH = resolve(__dirname, '../src/config/templates/generated.ts');

function resolveVersionPath(): string {
    const [majorStr, minorStr] = SING_BOX_MAJOR_VERSION.split('.');
    const patch = parseInt(SING_BOX_MINOR_VERSION, 10);
    if (!majorStr || !minorStr || Number.isNaN(patch)) {
        throw new Error(
            `invalid SING_BOX_VERSION: cannot parse "${SING_BOX_MAJOR_VERSION}.${SING_BOX_MINOR_VERSION}"`,
        );
    }
    if (majorStr === '1' && minorStr === '13' && patch >= 8) return '1.13.8';
    if (majorStr === '1' && minorStr === '13') return '1.13';
    if (majorStr === '1' && minorStr === '12') return '1.12';
    throw new Error(
        `unsupported sing-box version ${majorStr}.${minorStr}.${patch} — add a mapping in scripts/sync-templates.ts`,
    );
}

async function fetchText(url: string, label: string): Promise<string> {
    const controller = new AbortController();
    const timeoutId = setTimeout(() => controller.abort(), 30_000);
    try {
        const res = await fetch(url, { signal: controller.signal });
        if (!res.ok) {
            throw new Error(`${label}: HTTP ${res.status} ${res.statusText}`);
        }
        return await res.text();
    } finally {
        clearTimeout(timeoutId);
    }
}

async function fetchLatestSha(): Promise<string> {
    try {
        const res = await fetch(
            `https://api.github.com/repos/${REPO}/branches/${BRANCH}`,
            { headers: { 'User-Agent': 'aurestream-sync-templates' } },
        );
        if (!res.ok) return 'unknown';
        const json = (await res.json()) as { commit?: { sha?: string } };
        return json?.commit?.sha ?? 'unknown';
    } catch {
        return 'unknown';
    }
}

type FetchedMode = { mode: string; parsed: unknown };

function existingGeneratedAtForCommit(commitSha: string): string | undefined {
    if (!existsSync(OUTPUT_PATH) || commitSha === 'unknown') return undefined;
    const text = readFileSync(OUTPUT_PATH, 'utf-8');
    const existingCommit = text.match(/commit: '([^']+)'/)?.[1];
    if (existingCommit !== commitSha) return undefined;
    return text.match(/generatedAt: '([^']+)'/)?.[1];
}

function emitGeneratedFile(
    versionPath: string,
    commitSha: string,
    builtAt: string,
    fetched: FetchedMode[],
): string {
    const identFor: Record<string, string> = {
        'mixed': 'MIXED_TEMPLATE',
        'tun': 'TUN_TEMPLATE',
        'mixed-global': 'MIXED_GLOBAL_TEMPLATE',
        'tun-global': 'TUN_GLOBAL_TEMPLATE',
    };

    const constants = fetched
        .map((r) => {
            const body = JSON.stringify(r.parsed, null, 4);
            return `export const ${identFor[r.mode]} = ${body} as const;`;
        })
        .join('\n\n');

    const mapEntries = fetched
        .map((r) => `    '${r.mode}': ${identFor[r.mode]},`)
        .join('\n');

    return `// AUTO-GENERATED by scripts/sync-templates.ts — do not edit.
// Keep this file committed as the offline build-time fallback.
// Regenerate before release: pnpm run sync-templates
//
// Source:  https://github.com/${REPO}/tree/${BRANCH}/conf/${versionPath}/zh-cn
// Branch:  ${BRANCH}
// Commit:  ${commitSha}
// Built:   ${builtAt}
// sing-box: ${SING_BOX_VERSION}

import type { configType } from '../common';

export const BUILD_TIME_TEMPLATE_SOURCE = {
    repo: '${REPO}',
    branch: '${BRANCH}',
    commit: '${commitSha}',
    versionPath: '${versionPath}',
    singBoxVersion: '${SING_BOX_VERSION}',
    generatedAt: '${builtAt}',
} as const;

${constants}

export const BUILT_IN_TEMPLATE_OBJECTS: Record<configType, unknown> = {
${mapEntries}
};
`;
}

async function main(): Promise<void> {
    const versionPath = resolveVersionPath();
    const modes = Object.keys(MODE_TO_FILE);

    console.log(`[sync-templates] ${SING_BOX_VERSION} -> conf/${versionPath}/zh-cn/  (branch: ${BRANCH})`);

    let commitSha: string;
    let fetched: FetchedMode[];
    try {
        const results = await Promise.all([
            fetchLatestSha(),
            ...modes.map(async (mode): Promise<FetchedMode> => {
                const file = MODE_TO_FILE[mode];
                const url = `https://raw.githubusercontent.com/${REPO}/${BRANCH}/conf/${versionPath}/zh-cn/${file}`;
                const text = await fetchText(url, file);
                const errors: any[] = [];
                const parsed = parseJsonc(text, errors, { allowTrailingComma: true });
                if (errors.length > 0) {
                    throw new Error(
                        `${file}: jsonc parse errors\n` +
                            errors.map((e) => `  ${e.error} @offset ${e.offset}`).join('\n'),
                    );
                }
                if (!parsed || typeof parsed !== 'object') {
                    throw new Error(`${file}: did not parse as object`);
                }
                console.log(`[sync-templates]   ↓ ${file}`);
                return { mode, parsed };
            }),
        ]);
        commitSha = results[0] as string;
        fetched = results.slice(1) as FetchedMode[];
    } catch (e: any) {
        if (existsSync(OUTPUT_PATH)) {
            console.warn(
                `[sync-templates] fetch failed (${e?.message ?? e}); keeping existing snapshot at ${OUTPUT_PATH}`,
            );
            return;
        }
        throw e;
    }

    const builtAt = existingGeneratedAtForCommit(commitSha) ?? new Date().toISOString();
    const content = emitGeneratedFile(versionPath, commitSha, builtAt, fetched);
    mkdirSync(dirname(OUTPUT_PATH), { recursive: true });
    writeFileSync(OUTPUT_PATH, content, 'utf-8');

    console.log(`[sync-templates] wrote ${OUTPUT_PATH}`);
    console.log(`[sync-templates] done (commit: ${commitSha === 'unknown' ? 'unknown' : commitSha.slice(0, 8)})`);
}

main().catch((e) => {
    console.error(`[sync-templates] failed: ${e?.message ?? e}`);
    process.exit(1);
});
